// F007, F042: public/llms.txt and llms-full.txt, the files LLM agents ingest,
// were hand-written and stale: fabricated SDK code (`from x402.client import
// Client`, `new x402Client({ walletKey })` from "x402"), wrong prices, 8-hour
// funding, VIRTUAL-priced ACP, and no free /demo, MCP server or A2A. They are
// now generated by scripts/build-llms.mjs from the docs pages and src/data/.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { expectedFiles, loadData, mdxToMarkdown, sidebarSlugs } from '../scripts/build-llms.mjs';
import { ROOT, WRONG } from './lib.mjs';

const read = (p) => readFileSync(join(ROOT, p), 'utf8').replace(/\r\n/g, '\n');
const llms = read('public/llms.txt');
const full = read('public/llms-full.txt');

test('the committed llms files are what the generator builds', () => {
  for (const [path, content] of Object.entries(expectedFiles())) {
    assert.equal(readFileSync(path, 'utf8').replace(/\r\n/g, '\n'), content, `${path} is stale: node scripts/build-llms.mjs`);
  }
});

test('llms.txt follows the llms.txt format and names every way in', () => {
  assert.match(llms, /^# Cerebrus Pulse\n\n> /);
  const links = [...llms.matchAll(/^- \[[^\]]+\]\((https:\/\/[^)]+)\): \S/gm)].map((m) => m[1]);
  assert.ok(links.length >= 25, `only ${links.length} links`);
  for (const needed of ['/demo/BTC', '/guides/mcp-server', '/guides/python-client', '/guides/langchain',
    '/guides/a2a-agents', '/guides/acp-agents', '/openapi.yaml', '/openapi.json', '/.well-known/agent-card.json',
    '/.well-known/x402', '/llms-full.txt']) {
    assert.ok(links.some((l) => l.endsWith(needed)), needed);
  }
  const prices = loadData().prices;
  for (const r of prices.routes) {
    assert.ok(llms.includes(`- [GET ${r.path}](https://cerebruspulse.xyz/api/${r.endpoint}): $${r.price} USDC.`), r.path);
  }
});

test('llms-full.txt carries every docs page, fully converted', () => {
  for (const slug of sidebarSlugs()) assert.match(full, new RegExp(`^Source: https://cerebruspulse\.xyz/${slug}$`, 'm'), slug);
  // MDX imports (code blocks keep their own imports), tabs and components
  assert.doesNotMatch(full, /^import .* from '(\.\.\/|@astrojs\/)|<\/?(Tabs|TabItem)\b|<[A-Z]\w+ [^>]*\/>/m);
  assert.doesNotMatch(full, /\]\(\/[^/]/, 'relative links');
});

test('neither file carries fabricated SDK code or a retired claim', () => {
  for (const text of [llms, full]) {
    assert.doesNotMatch(text, /from x402\.client import Client|from ["']x402["']|new x402Client\(\{|walletKey|createSigner\(/);
    assert.doesNotMatch(text, /npm install x402-fetch|\bVIRTUAL\b|\d+% (discount|cheaper)|multi-model|acp\.(createJob|waitForJob|discover)/i);
    for (const [pattern, why] of WRONG) assert.doesNotMatch(text, pattern, why);
  }
});

test('the MDX converter expands components and keeps code verbatim', () => {
  const data = loadData();
  const page = [
    '---', 'title: T', '---', '', "import X from 'y';", '',
    '# GET /pulse/\{coin\}', '', '<PriceBadge endpoint="pulse" />', '',
    ':::note[Heads up]', 'Two lines', 'of text', ':::', '',
    '<Tabs>', '  <TabItem label="Base">', '    ```bash', '    pip install "x" "<0.37"', '    ```', '  </TabItem>', '</Tabs>',
    '', 'See [the guide](/quickstart).',
  ].join('\n');
  const md = mdxToMarkdown(page, data);
  assert.match(md, /^# GET \/pulse\/\{coin\}$/m);
  assert.match(md, /^\*\*Price:\*\* \$0\.025 USDC per call$/m);
  assert.match(md, /^> \*\*Heads up:\*\*\n> Two lines\n> of text$/m);
  assert.match(md, /^\*\*Base:\*\*\n\n```bash\npip install "x" "<0\.37"\n```$/m);
  assert.match(md, /\(https:\/\/cerebruspulse\.xyz\/quickstart\)/);
  assert.throws(() => mdxToMarkdown('<Unknown thing="x" />', data), /no markdown for <Unknown \/>/);
});
