// F006: public/openapi.yaml was hand-written and disagreed with the engine
// (field names, a discount_pct field, 8-hour funding). It is now generated by
// scripts/sync-gateway.mjs (scripts/openapi.mjs) from the payment routes, real
// engine responses and the parameters the gateway validates.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import yaml from 'js-yaml';
import { queryParams, schemaOf } from '../scripts/openapi.mjs';
import { ROOT } from './lib.mjs';

const read = (p) => readFileSync(join(ROOT, p), 'utf8');
const spec = yaml.load(read('public/openapi.yaml'));
const prices = JSON.parse(read('src/data/prices.json'));
const examples = JSON.parse(read('src/data/response-examples.json'));

test('every paid route is in the spec at the charged price, and nothing else is paid', () => {
  assert.equal(spec.openapi, '3.1.0');
  assert.equal(spec.info.version, prices.api_version);
  assert.equal(spec['x-payment'].header, 'PAYMENT-SIGNATURE');
  const paid = Object.entries(spec.paths).filter(([, v]) => v.get['x-price-usd'] > 0);
  assert.equal(paid.length, prices.routes.length);
  for (const route of prices.routes) {
    assert.equal(spec.paths[route.path].get['x-price-usd'], Number(route.price), route.path);
  }
  for (const free of ['/health', '/coins', '/demo/{coin}']) assert.ok(spec.paths[free], free);
});

test('response examples and schemas are the real engine output', () => {
  for (const route of prices.routes) {
    const content = spec.paths[route.path].get.responses['200'].content['application/json'];
    const example = examples.examples[route.endpoint];
    if (!example) {
      assert.deepEqual(content.schema, { type: 'object' }, route.path);
      continue;
    }
    assert.deepEqual(content.example, example, route.path);
    assert.deepEqual(content.schema, schemaOf(example), route.path);
  }
});

test('query parameters are the ones the gateway validates, with its ranges and defaults', () => {
  const byPath = Object.fromEntries(
    Object.entries(spec.paths).map(([p, v]) => [p, Object.fromEntries((v.get.parameters || []).map((x) => [x.name, x]))])
  );
  assert.deepEqual(byPath['/funding/{coin}'].lookback_hours.schema, { type: 'integer', minimum: 1, maximum: 168, default: 24 });
  assert.deepEqual(byPath['/screener'].top_n.schema, { type: 'integer', minimum: 1, maximum: 50, default: 50 });
  assert.deepEqual(byPath['/arb'].limit.schema, { type: 'integer', minimum: 1, maximum: 50, default: 10 });
  assert.deepEqual(byPath['/correlation'].window.schema.enum, ['30h', '7d', '30d']);
  assert.equal(byPath['/pulse/{coin}'].timeframes.schema.default, '1h,4h');
  assert.equal(byPath['/cex-dex/{token}'].token.in, 'path');
});

test('the parameter reader follows the gateway source', () => {
  const server = [
    'CORRELATION_WINDOWS = ("30h", "7d")',
    'VALID_TIMEFRAMES = ("1h", "4h")',
    'TIMEFRAME_PREFIXES = ("/pulse/",)',
    'INT_PARAMS = {',
    '    "/screener": {"top_n": (1, 20)},',
    '}',
    '@app.get("/pulse/{coin}", **PAID_ROUTE)',
    'async def pulse(coin: str, timeframes: str = "1h,4h"):',
    '@app.get("/screener", **PAID_ROUTE)',
    'async def screener(top_n: int = 20):',
    '@app.get("/sentiment", **PAID_ROUTE)',
    'async def sentiment():',
  ].join('\n');
  const params = queryParams(server);
  assert.deepEqual(params.screener[0].schema, { type: 'integer', minimum: 1, maximum: 20, default: 20 });
  assert.equal(params.pulse[0].description, 'Comma-separated, from 1h,4h (default 1h,4h)');
  assert.deepEqual(params.sentiment, []);
  assert.throws(
    () => queryParams(server.replace('async def sentiment():', 'async def sentiment(depth: int = 5):')),
    /no OpenAPI rule for \/sentiment parameter depth/
  );
});
